FROM ghcr.io/deck-app/nginx:v5.6
LABEL maintainer Naba Das <hello@get-deck.com>

# Persistent runtime dependencies
# Example RUN apk add --no-cache php5-openssl php5-sysvmsg php5-curl

# Create custom user and group
RUN groupadd  myuser \
    && useradd -g myuser -m myuser \
    && usermod -p "*" myuser -s /bin/bash \
    && echo "myuser:myuser" | chpasswd

COPY default.conf /etc/nginx/conf.d/default.conf
ARG SERVER_ROOT
RUN sed -i "s#{SERVER_ROOT}#$SERVER_ROOT#g" /etc/nginx/conf.d/default.conf
VOLUME [ "/var/www/" ]
WORKDIR /var/www
COPY php_ini/php.ini /etc/php5/php.ini

ARG DISPLAY_PHPERROR
RUN if [ ${DISPLAY_PHPERROR} = true ]; then \
sed -i "s#{DISPLAY}#On#g" /etc/php5/php.ini \
;else \
sed -i "s#{DISPLAY}#Off#g" /etc/php5/php.ini \
;fi

#mongodb version update not supported
#pecl install mongodb \
#&& echo "extension=mongodb.so" > /etc/php5/conf.d/mongodb.ini

ARG INSTALL_ADDITIONAL_EXTENSIONS
RUN if [ -z "$INSTALL_ADDITIONAL_EXTENSIONS" ] ; then \
echo "No additional PHP extensions added" \
;else \
apk add --no-cache ${INSTALL_ADDITIONAL_EXTENSIONS} \
;fi

## Linux permission issue
ARG USER_ID
ARG GROUP_ID
RUN apk --no-cache add shadow
RUN usermod -u ${USER_ID} myuser && groupmod -g ${GROUP_ID} myuser
RUN sed -i 's/user nginx/user myuser/g' /etc/nginx/nginx.conf

#Xdebug enable or disable
ARG XDEBUG
RUN if [ ${XDEBUG} = true ]; then \
pecl install xdebug-2.5.5 \
&& echo "zend_extension=/usr/lib/php5/modules/xdebug.so" >> /etc/php5/php.ini \
;fi