name: Nginx Stack

on:
  schedule:
  - cron:  '30 5,17 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Nginx-PHP8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image nginx php 8.0
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
          PHP_VERSION: "8.0"
          XDEBUG: true
          DISPLAY_PHPERROR: true
          SERVER_ROOT:  /var/www/
          APP_CODE_PATH_HOST: /tmp/app
    - name: PHP version check
      run : docker exec nginx-stack_nginx_1 php -v
    - name: Mongodb driver check
      run:  docker exec nginx-stack_nginx_1 php -m | grep mongo
    - name: Mysql Driver check
      run: docker exec nginx-stack_nginx_1 php -m | grep mysqli
    - name: Composer test
      run: docker exec nginx-stack_nginx_1 composer
    - name: Web site Test
      run: |
        sudo echo "<?php phpinfo(); ?>" >> /tmp/app/index.php
        sudo curl -I --http2 http://localhost:5647/ | grep HTTP
    - name: Laravel8 test
      run:  docker exec nginx-stack_nginx_1 composer create-project --prefer-dist laravel/laravel:^8.0
    - name: Destroy Container and file
      run:  |
        docker-compose down
        sudo rm -rf /tmp/app

  # Nginx-PHP7:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build the Docker image nginx php 7.4
  #     run: docker-compose -f "docker-compose.yml" up -d --build
  #     env:
  #         PHP_VERSION: "7.4"
  #         XDEBUG: true
  #         DISPLAY_PHPERROR: true
  #         SERVER_ROOT:  /var/www/
  #         APP_CODE_PATH_HOST: /tmp/app
  #   - name: PHP version check
  #     run : docker exec nginx-stack_nginx_1 php -v
  #   - name: Mongodb driver check
  #     run:  docker exec nginx-stack_nginx_1 php -m | grep mongo
  #   - name: Mysql Driver check
  #     run: docker exec nginx-stack_nginx_1 php -m | grep mysqli
  #   - name: Composer test
  #     run: docker exec nginx-stack_nginx_1 composer
  #   - name: Web site Test
  #     run: |
  #       docker exec nginx-stack_nginx_1 -e echo "<?php phpinfo(); ?>" > /var/www/index.php
  #       curl -I --http2 http://localhost:5647/ | grep HTTP
  #   - name: Laravel8 test
  #     run:  docker exec nginx-stack_nginx_1 composer create-project --prefer-dist laravel/laravel:^8.0
  #   - name: Destroy Container and file
  #     run:  |
  #       docker-compose down
  #       sudo rm -rf /tmp/app
  
  # Nginx-PHP5: 
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build the Docker image nginx php 5.6
  #     run: docker-compose -f "docker-compose.yml" up -d --build
  #     env:
  #         PHP_VERSION: "5.6"
  #         XDEBUG: true
  #         DISPLAY_PHPERROR: true
  #         SERVER_ROOT:  /var/www/
  #         APP_CODE_PATH_HOST: /tmp/app
  #   - name: PHP version check
  #     run : docker exec nginx-stack_nginx_1 php -v
  #   - name: Mysql Driver check
  #     run: docker exec nginx-stack_nginx_1php -m | grep mysqli
  #   - name: Composer test
  #     run: docker exec nginx-stack_nginx_1 composer
  #   - name: Web site Test
  #     run: |
  #       docker exec nginx-stack_nginx_1 echo "<?php phpinfo(); ?>" > /var/www/index.php
  #       curl -I --http2 http://localhost:5647/ | grep HTTP
  #   - name: Laravel8 test
  #     run:  docker exec nginx-stack_nginx_1 composer create-project --prefer-dist laravel/laravel:^8.0
  #   - name: Destroy Container and file
  #     run:  |
  #       docker-compose down
  #       sudo rm -rf /tmp/app
