name: Docker Multi-Arch Container

on:
  push:
    branches: [ image ]
env:
  IMAGE_NAME: nginx
  VERSION: v8.0

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - uses: president-business-corp/simple-docker/metadata@trunk
        id: metadata
        with:
          image-name: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/amd64,linux/arm64,linux/386

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to GHCR
        uses: docker/login-action@v1 
        with:
          registry: https://${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ${{ steps.metadata.outputs.file }}
          platforms: ${{ steps.qemu.outputs.platforms }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          build-args: ${{ steps.metadata.outputs.args }}
          labels: ${{ steps.metadata.outputs.labels }}